spring:
  application:
    name: ${artifactId}
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /${artifactId}

---
spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, threaddump, heapdump, scheduledtasks, loggers, prometheus
      base-path: /status
  metrics:
    tags:
     application: ${spring.application.name}
    distribution:
      percentiles[http.server.requests]: 0.5, 0.6, 0.7, 0.95, 0.99, 1.0
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

info:
  app:
    name: Certificate Service
    description: Certificate Service manages certificates
    version: 0.0.1

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      barco:
        eis:
          auditservice: DEBUG

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /doc
    enabled: true

---
spring:
  config:
    activate:
      on-profile: devstable

  devtools:
    add-properties: false
    restart:
      enabled: false

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, threaddump, heapdump, scheduledtasks, loggers, prometheus
      base-path: /status
  metrics:
    tags:
     application: ${spring.application.name}
    distribution:
      percentiles[http.server.requests]: 0.5, 0.6, 0.7, 0.95, 0.99, 1.0
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

info:
  app:
    name: Certificate Service
    description: Certificate Service manages certificates
    version: 0.0.1

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      barco:
        eis:
          auditservice: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /doc
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

  devtools:
    add-properties: false
    restart:
      enabled: false

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, threaddump, heapdump, scheduledtasks, loggers, prometheus
      base-path: /status
  metrics:
    tags:
     application: ${spring.application.name}
    distribution:
      percentiles[http.server.requests]: 0.5, 0.6, 0.7, 0.95, 0.99, 1.0
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

info:
  app:
    name: Certificate Service
    description: Certificate Service manages certificates
    version: 0.0.1

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      barco:
        eis:
          auditservice: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

